package com.weight.model;
// Generated 16 f�vr. 2025, 21:22:45 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * PriseEnCharge generated by hbm2java
 */
@Entity
@Table(name = "prise_en_charge")
public class PriseEnCharge implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPrise;
	private Colis colis;
	private Statuts statuts;
	private Users users;
	private String idVol;
	private String villeDepart;
	private Date dateDepart;
	private String villeArrivee;
	private Date dateArrivee;

	public PriseEnCharge() {
	}
	
	public PriseEnCharge(Users users, String idVol, String villeDepart, String villeArrivee) {
		this.users = users;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
	}

	public PriseEnCharge(int idPrise, Colis colis, Users users, String idVol, String villeDepart, String villeArrivee) {
		this.idPrise = idPrise;
		this.colis = colis;
		this.users = users;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
	}

	public PriseEnCharge(int idPrise, Colis colis, Statuts statuts, Users users, String idVol, String villeDepart,
			Date dateDepart, String villeArrivee, Date dateArrivee) {
		this.idPrise = idPrise;
		this.colis = colis;
		this.statuts = statuts;
		this.users = users;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.dateDepart = dateDepart;
		this.villeArrivee = villeArrivee;
		this.dateArrivee = dateArrivee;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prise", unique = true, nullable = false)
	public int getIdPrise() {
		return this.idPrise;
	}

	public void setIdPrise(int idPrise) {
		this.idPrise = idPrise;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_colis")
	public Colis getColis() {
		return this.colis;
	}

	public void setColis(Colis colis) {
		this.colis = colis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_statut")
	public Statuts getStatuts() {
		return this.statuts;
	}

	public void setStatuts(Statuts statuts) {
		this.statuts = statuts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user_preneur", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "id_vol", nullable = false, length = 50)
	public String getIdVol() {
		return this.idVol;
	}

	public void setIdVol(String idVol) {
		this.idVol = idVol;
	}

	@Column(name = "ville_depart", nullable = false, length = 50)
	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_depart", length = 19)
	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	@Column(name = "ville_arrivee", nullable = false, length = 50)
	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_arrivee", length = 19)
	public Date getDateArrivee() {
		return this.dateArrivee;
	}

	public void setDateArrivee(Date dateArrivee) {
		this.dateArrivee = dateArrivee;
	}

}
