package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Statuts generated by hbm2java
 */
@Entity
@Table(name = "STATUTS")
@JsonIgnoreProperties({"hibernateLazyInitializer"})
public class Statuts implements java.io.Serializable, Comparable<Statuts> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID_STATUT")
	private int idStatut;
	
	@Column(name = "LIBEL_STATUT")
	private String libelStatut;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuts")
	private Set<UsersDispo> usersDispos = new HashSet<UsersDispo>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuts")
	private Set<UserTrade> userTrades = new HashSet<UserTrade>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuts")
	private Set<TranspDispo> transpDispos = new HashSet<TranspDispo>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuts")
	private Set<TranspTrade> transpTrades = new HashSet<TranspTrade>(0);


	public Statuts() {
	}

	public Statuts(int idStatut) {
		this.idStatut = idStatut;
	}


	public Statuts(int idStatut, String libelStatut, Set<UsersDispo> usersDispos, Set<UserTrade> userTrades,
			Set<TranspDispo> transpDispos, Set<TranspTrade> transpTrades) {
		this.idStatut = idStatut;
		this.libelStatut = libelStatut;
		this.usersDispos = usersDispos;
		this.userTrades = userTrades;
		this.transpDispos = transpDispos;
		this.transpTrades = transpTrades;
	}

	
	public int getIdStatut() {
		return this.idStatut;
	}

	public void setIdStatut(int idStatut) {
		this.idStatut = idStatut;
	}

	public String getLibelStatut() {
		return this.libelStatut;
	}

	public void setLibelStatut(String libelStatut) {
		this.libelStatut = libelStatut;
	}

	public Set<UsersDispo> getUsersDispos() {
		return this.usersDispos;
	}

	public void setUsersDispos(Set<UsersDispo> usersDispos) {
		this.usersDispos = usersDispos;
	}

	public Set<UserTrade> getUserTrades() {
		return this.userTrades;
	}

	public void setUserTrades(Set<UserTrade> userTrades) {
		this.userTrades = userTrades;
	}

	public Set<TranspDispo> getTranspDispos() {
		return this.transpDispos;
	}

	public void setTranspDispos(Set<TranspDispo> transpDispos) {
		this.transpDispos = transpDispos;
	}

	public Set<TranspTrade> getTranspTrades() {
		return this.transpTrades;
	}

	public void setTranspTrades(Set<TranspTrade> transpTrades) {
		this.transpTrades = transpTrades;
	}

	@Override
	public int compareTo(Statuts o) {
		return this.getLibelStatut().compareTo(o.getLibelStatut());
	}
	
}
