package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Transporteurs generated by hbm2java
 */
@Entity
@Table(name = "TRANSPORTEURS")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Transporteurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID_TRANSP", unique = true, nullable = false, length = 50)
	private String idTransp;
	
	@Column(name = "NOM", length = 50)
	private String nom;
	
	@Column(name = "MAIL", length = 30)
	private String mail;

	public Transporteurs() {
	}

	public Transporteurs(String idTransp) {
		this.idTransp = idTransp;
	}

	public Transporteurs(String idTransp, String nom, String mail) {
		this.idTransp = idTransp;
		this.nom = nom;
		this.mail = mail;
	}

	public String getIdTransp() {
		return this.idTransp;
	}

	public void setIdTransp(String idTransp) {
		this.idTransp = idTransp;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
