package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * TranspDispo generated by hbm2java
 */
@Entity
@Table(name = "TRANSP_DISPO")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TranspDispo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_dispo", unique = true, nullable = false)
	private int idDispo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STATUT")
	private Statuts statuts;
	
	@Column(name = "ID_TRANSP_DISPO")
	private String idTranspDispo;
	
	@Column(name = "ID_VOL")
	private String idVol;
	
	@Column(name = "VILLE_DEPART")
	private String villeDepart;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_DEPART")
	private Date dateDepart;
	
	@Column(name = "VILLE_ARRIVEE")
	private String villeArrivee;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ARRIVEE")
	private Date dateArrivee;
	
	
	@Column(name = "NB_KILO_DISPO")
	private Integer nbKiloDispo;

	public TranspDispo() {
	}

	public TranspDispo(int idDispo, String idTranspDispo, String idVol, String villeDepart, String villeArrivee) {
		this.idDispo = idDispo;
		this.idTranspDispo = idTranspDispo;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
	}

	public TranspDispo(int idDispo, Statuts statuts, String idTranspDispo, String idVol, String villeDepart,
			Date dateDepart, String villeArrivee, Date dateArrivee, Integer nbKiloDispo) {
		this.idDispo = idDispo;
		this.statuts = statuts;
		this.idTranspDispo = idTranspDispo;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.dateDepart = dateDepart;
		this.villeArrivee = villeArrivee;
		this.dateArrivee = dateArrivee;
		this.nbKiloDispo = nbKiloDispo;
	}

	public int getIdDispo() {
		return this.idDispo;
	}

	public void setIdDispo(int idDispo) {
		this.idDispo = idDispo;
	}

	public Statuts getStatuts() {
		return this.statuts;
	}

	public void setStatuts(Statuts statuts) {
		this.statuts = statuts;
	}

	public String getIdTranspDispo() {
		return this.idTranspDispo;
	}

	public void setIdTranspDispo(String idTranspDispo) {
		this.idTranspDispo = idTranspDispo;
	}

	public String getIdVol() {
		return this.idVol;
	}

	public void setIdVol(String idVol) {
		this.idVol = idVol;
	}

	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	public Date getDateArrivee() {
		return this.dateArrivee;
	}

	public void setDateArrivee(Date dateArrivee) {
		this.dateArrivee = dateArrivee;
	}

	public Integer getNbKiloDispo() {
		return this.nbKiloDispo;
	}

	public void setNbKiloDispo(Integer nbKiloDispo) {
		this.nbKiloDispo = nbKiloDispo;
	}

}
