package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UsersProfilId generated by hbm2java
 */
@Embeddable
public class UsersProfilId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "id_user")
	private String idUser;
	
	@Column(name = "id_profil")
	private int idProfil;

	public UsersProfilId() {
	}

	public UsersProfilId(String idUser, int idProfil) {
		this.idUser = idUser;
		this.idProfil = idProfil;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public int getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(int idProfil) {
		this.idProfil = idProfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersProfilId))
			return false;
		UsersProfilId castOther = (UsersProfilId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null
				&& castOther.getIdUser() != null && this.getIdUser().equals(castOther.getIdUser())))
				&& (this.getIdProfil() == castOther.getIdProfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result + this.getIdProfil();
		return result;
	}

}
