package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * UsersProfil generated by hbm2java
 */
@Entity
@Table(name = "USERS_PROFIL")
@JsonIgnoreProperties({"hibernateLazyInitializer"})
public class UsersProfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idProfil", column = @Column(name = "id_profil", nullable = false)) })
	private UsersProfilId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROFIL",nullable = false, insertable = false, updatable = false)
	private Profil profil;
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", nullable = false, insertable = false, updatable = false)
	private Users users;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_init")
	private Date dateInit;
	
	@Column(name = "note")
	private Long note;

	public UsersProfil() {
	}

	public UsersProfil(UsersProfilId id, Profil profil, Users users) {
		this.id = id;
		this.profil = profil;
		this.users = users;
	}

	public UsersProfil(UsersProfilId id, Profil profil, Users users, Date dateInit, Long note) {
		this.id = id;
		this.profil = profil;
		this.users = users;
		this.dateInit = dateInit;
		this.note = note;
	}

	public UsersProfilId getId() {
		return this.id;
	}

	public void setId(UsersProfilId id) {
		this.id = id;
	}

	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getDateInit() {
		return this.dateInit;
	}

	public void setDateInit(Date dateInit) {
		this.dateInit = dateInit;
	}

	public Long getNote() {
		return this.note;
	}

	public void setNote(Long note) {
		this.note = note;
	}

}
