package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Users implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id_user")
	private String idUser;
	
	@Column(name = "nom")
	private String nom;
	@Column(name = "prenom")
	private String prenom;
	@Column(name = "mail")
	private String mail;
	@Column(name = "password")
	private String password;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
	private Set<UsersProfil> usersProfils = new HashSet<UsersProfil>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<UsersDispo> usersDispos = new HashSet<UsersDispo>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<UserTrade> userTrades = new HashSet<UserTrade>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<TranspTrade> transpTrades = new HashSet<TranspTrade>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<HistAvis> histAvises = new HashSet<HistAvis>(0);	
	

	
	public Users() {
	}

	public Users(String idUser) {
		this.idUser = idUser;
	}

	
	public Users(String idUser, String nom, String prenom, String mail, String password, Set<UsersProfil> usersProfils,
			Set<TranspTrade> transpTrades, Set<HistAvis> histAvises, Set<UsersDispo> usersDispos,
			Set<UserTrade> userTrades) {
		super();
		this.idUser = idUser;
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.password = password;
		this.usersProfils = usersProfils;
		this.transpTrades = transpTrades;
		this.histAvises = histAvises;
		this.usersDispos = usersDispos;
		this.userTrades = userTrades;
	}


	public Users(String idUser, String nom, String prenom, String mail, String password,
			Set<UsersProfil> usersProfils) {
		super();
		this.idUser = idUser;
		this.nom = nom;
		this.prenom = prenom;
		this.mail = mail;
		this.password = password;
		this.usersProfils = usersProfils;
	}

	public String getIdUser() {
		return idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}



	public Set<UsersProfil> getUsersProfils() {
		return usersProfils;
	}

	public void setUsersProfils(Set<UsersProfil> usersProfils) {
		this.usersProfils = usersProfils;
	}


	public Set<TranspTrade> getTranspTrades() {
		return transpTrades;
	}

	public void setTranspTrades(Set<TranspTrade> transpTrades) {
		this.transpTrades = transpTrades;
	}

	public Set<HistAvis> getHistAvises() {
		return histAvises;
	}

	public void setHistAvises(Set<HistAvis> histAvises) {
		this.histAvises = histAvises;
	}

	public Set<UsersDispo> getUsersDispos() {
		return usersDispos;
	}

	public void setUsersDispos(Set<UsersDispo> usersDispos) {
		this.usersDispos = usersDispos;
	}

	public Set<UserTrade> getUserTrades() {
		return userTrades;
	}

	public void setUserTrades(Set<UserTrade> userTrades) {
		this.userTrades = userTrades;
	}
	
}
