package com.weight.model;
// Generated 1 oct. 2023, 21:30:36 by Hibernate Tools 5.4.33.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * UsersDispo generated by hbm2java
 */
@Entity
@Table(name = "users_dispo")
@JsonIgnoreProperties({"hibernateLazyInitializer"})
public class UsersDispo implements java.io.Serializable,Comparable<UsersDispo> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_dispo")
	private int idDispo;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_statut", nullable = false, insertable = false, updatable = false)
	private Statuts statuts;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user_dispo",referencedColumnName="id_user", nullable = false, insertable = false, updatable = false)
	private Users users;
	
	@Column(name = "id_vol")
	private String idVol;
/*	
	@Column(name = "AERONOM_DEPART")
	private String aeronomDepart;
*/	
	@Column(name = "ville_depart")
	private String villeDepart;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_depart")
	private Date dateDepart;
/*	
	@Column(name = "AERONOM_ARRIVEE")
	private String aeronomArrivee;
*/	
	@Column(name = "ville_arrivee")
	private String villeArrivee;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_arrivee")
	private Date dateArrivee;
	
	@Column(name = "nb_kilo_dispo")
	private Integer nbKiloDispo;

	public UsersDispo() {
	}

	public UsersDispo(int idDispo, Users users, String idVol, String villeDepart, String villeArrivee) {
		this.idDispo = idDispo;
		this.users = users;
		this.idVol = idVol;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
	}

/*
	public UsersDispo(int idDispo, Statuts statuts, Users users, String idVol, String aeronomDepart, String villeDepart,
			Date dateDepart, String aeronomArrivee, String villeArrivee, Date dateArrivee, Integer nbKiloDispo) {
		super();
		this.idDispo = idDispo;
		this.statuts = statuts;
		this.users = users;
		this.idVol = idVol;
		this.aeronomDepart = aeronomDepart;
		this.villeDepart = villeDepart;
		this.dateDepart = dateDepart;
		this.aeronomArrivee = aeronomArrivee;
		this.villeArrivee = villeArrivee;
		this.dateArrivee = dateArrivee;
		this.nbKiloDispo = nbKiloDispo;
	}
*/
	public int getIdDispo() {
		return this.idDispo;
	}

	public void setIdDispo(int idDispo) {
		this.idDispo = idDispo;
	}

	public Statuts getStatuts() {
		return this.statuts;
	}

	public void setStatuts(Statuts statuts) {
		this.statuts = statuts;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getIdVol() {
		return this.idVol;
	}

	public void setIdVol(String idVol) {
		this.idVol = idVol;
	}

	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	public Date getDateArrivee() {
		return this.dateArrivee;
	}

	public void setDateArrivee(Date dateArrivee) {
		this.dateArrivee = dateArrivee;
	}

	public Integer getNbKiloDispo() {
		return this.nbKiloDispo;
	}

	public void setNbKiloDispo(Integer nbKiloDispo) {
		this.nbKiloDispo = nbKiloDispo;
	}

	/*
	public String getAeronomDepart() {
		return aeronomDepart;
	}

	public void setAeronomDepart(String aeronomDepart) {
		this.aeronomDepart = aeronomDepart;
	}

	public String getAeronomArrivee() {
		return aeronomArrivee;
	}

	public void setAeronomArrivee(String aeronomArrivee) {
		this.aeronomArrivee = aeronomArrivee;
	}
*/
	@Override
	public int compareTo(UsersDispo o) {
		return this.getDateDepart().compareTo(o.getDateDepart());
	}

}
